apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

secretGenerator:
  - name: majortom-tls
    namespace: majortom
    type: "kubernetes.io/tls"
    files:
      - secret/tls.crt
      - secret/tls.key
